// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7w4nqahxmU1ygJPEW6v7NiIknx25lyPY',
    appId: '1:475628769043:android:365778f5ef51bd164354e6',
    messagingSenderId: '475628769043',
    projectId: 'sakinah-flow',
    storageBucket: 'sakinah-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBoJ6Hs3pRopPMlPKTVF6bO71GBuW_u-A',
    appId: '1:475628769043:ios:5c229b055a3c09794354e6',
    messagingSenderId: '475628769043',
    projectId: 'sakinah-flow',
    storageBucket: 'sakinah-flow.firebasestorage.app',
    androidClientId: '475628769043-09jkjar0thi8l2moc6jap1l8evtofof3.apps.googleusercontent.com',
    iosClientId: '475628769043-kbv1gio00e338472hev7cl9lt46634b8.apps.googleusercontent.com',
    iosBundleId: 'com.sakinahflow.app',
  );
}
